In [2]:
import xarray as xr
import numpy as np

In [17]:
ds = xr.Dataset({
    'var1': (('x','y'), np.random.rand(4,5)),
    'var2': (('x','y'), np.random.rand(4,5))
})

In [34]:
#assign some coordinates to the dimensions x,y just for show:
x_values = [1,2,3,4]  #equally could use label values of 'x1', 'x2', 'x3', 'x4' for example
ds = ds.assign_coords(coords=dict
    (
    x=x_values,
    y=['y1','y2','y3','y4','y5']
    )
)  #could have others here too

In [32]:
#same thing using curly brackets:
#assign some coordinates to the dimensions x,y just for show:
x_values = [1,2,3,4]  #equally could use label values of 'x1', 'x2', 'x3', 'x4' for example
ds = ds.assign_coords({"x":x_values,
                       "y":['y1','y2','y3','y4','y5']
                      })


In [35]:
ds.sel(x=1).isel(y=0).values()

ValuesView(<xarray.Dataset> Size: 32B
Dimensions:  ()
Coordinates:
    x        int64 8B 1
    y        <U2 8B 'y1'
Data variables:
    var1     float64 8B 0.4645
    var2     float64 8B 0.7176)

In [110]:
ds = xr.Dataset({
    'var1': (('x', 'y'), np.random.rand(4, 5)),
    'var2': (('x', 'y'), np.random.rand(4, 5))
})
#new_dim_values = ['a', 'b', 'c']
ds['var2'] = ds['var2'].expand_dims({'new_dim': ['a','b','c']})
#ds = ds.assign_coords({'new_dim':['a','b','c']})
#ds['var2'] = ds.assign_coords({'new_dim':['a','b','c']})
ds.transpose('y','x','new_dim')

<xarray.Dataset> Size: 664B
Dimensions:  (x: 4, y: 5, new_dim: 3)
Coordinates:
  * new_dim  (new_dim) object 24B 'a' 'b' 'c'
Dimensions without coordinates: x, y
Data variables:
    var1     (y, x) float64 160B 0.3537 0.9132 0.2349 ... 0.2974 0.4844 0.5938
    var2     (y, x, new_dim) float64 480B 0.08847 0.08847 ... 0.8987 0.8987

In [75]:
x = np.array([9,99,999])
np.shape(x)

(3,)

In [93]:
np.shape(np.array(ds['var2']).T)

(5, 4, 3)

In [95]:
np.array(ds['var2']).T @  x

array([[  32.3509441 ,  936.05610903,  230.60420584,  846.94665061],
       [ 428.84259306,  233.17810092,  813.89136435,  288.72280356],
       [ 944.39232398,  157.80045852,  317.05277079,  420.64547512],
       [ 404.73197407,   81.32188146,  555.40483413,  502.42490781],
       [1031.54468461,  387.02615591, 1080.54337985,  142.54932545]])

In [89]:
# Create a matrix and a vector
matrix = np.array([[1, 2], [3, 4], [-1,-3]])
vector = np.array([5, 6,7])
print(np.shape(matrix.T))
print(np.shape(vector))
# Perform matrix-vector multiplication
result = matrix.T @ vector
#
print(result)

(2, 3)
(3,)
[16 13]


In [105]:
v = vector
m = matrix
v[:]
m[:,0]
print(v,'\n',m,'\n')
print(sum(v[:] * m[:,0]))

[5 6 7] 
 [[ 1  2]
 [ 3  4]
 [-1 -3]] 
 16


ChatGPT advised:
import xarray as xr
import numpy as np

# Assume ds is your existing Dataset
ds = xr.Dataset({
    'var1': (('x', 'y'), np.random.rand(4, 5)),
    'var2': (('x', 'y'), np.random.rand(4, 5))
})

# Define new dimension values
new_dim_values = ['a', 'b', 'c']

# Add new dimension to coordinates (optional)
ds = ds.assign_coords(new_dim=new_dim_values)

Step 2: Expand Specific Variables to Include the New Dimension

Only the variables that need the new dimension should be expanded.

python

# Expand 'var2' to include 'new_dim'
ds['var2'] = ds['var2'].expand_dims('new_dim')

# Alternatively, expand and assign in one step
ds['var2'] = ds['var2'].expand_dims({'new_dim': new_dim_values})

Now, var2 has the dimensions ('new_dim', 'x', 'y'), while var1 remains with dimensions ('x', 'y').
Step 3: (Optional) Add a New Variable with the New Dimension

If you're adding a new variable that uses the new dimension:

python

# Create data for the new variable
data = np.random.rand(3, 4, 5)  # Shape corresponds to ('new_dim', 'x', 'y')

# Add the new variable to the Dataset
ds['var3'] = (('new_dim', 'x', 'y'), data)

Verification

Check the dimensions of each variable to confirm they are as expected:

python

print(ds)

Output:

go

<xarray.Dataset>
Dimensions:   (x: 4, y: 5, new_dim: 3)
Coordinates:
  * new_dim   (new_dim) <U1 'a' 'b' 'c'
Dimensions without coordinates: x, y
Data variables:
    var1      (x, y) float64 0.8366 0.7465 ... 0.8473 0.5941
    var2      (new_dim, x, y) float64 0.1438 0.01903 ... 0.7659 0.9578
    var3      (new_dim, x, y) float64 0.4234 0.2077 ... 0.00741 0.7446

As you can see:

    var1 has dimensions ('x', 'y')
    var2 and var3 have dimensions ('new_dim', 'x', 'y')

Summary

    Variables Not Expanded: Remain unaffected by the new dimension.
    Variables Expanded: Only these variables include the new dimension.
    Dataset Coordinates: Can include the new dimension without forcing it onto all variables.

By selectively expanding variables, you maintain control over which ones inherit the new dimension.